### ISSUE TITLE
associate bot ID with bot user ID in storage

### ISSUE THREAD

**Issue by mvaragnat** [slackhq/node-slack-sdk#182]
the RTM.start method returns bot users (ID like UXXX, is_bot = true) as well as bots/integrations (ID like BXXX). The user field, if it's a bot, includes the corresponding bot/integration ID. 

However, this property disappears in storage - we get two separate lists of users ID and bot IDs. This make it difficult to reconcile. Here is a use case : the bot_message event returns a BXXX ID, while slack.activeUserId stores the UXXX ID, so it's difficult to know if that bot_message came from the current app.

Would it be possible to attach the bot ID to the user ID ?

**Comment by l12s** [comment]
Sorry for letting this issue go for so long.

Does https://github.com/slackhq/node-slack-sdk/pull/229 fix this for you?

**Comment by l12s** [comment]
I merged the PR, but let me know if you want anything different
