### ISSUE TITLE
Default to MemoryDataStore

### ISSUE THREAD

**Issue by ekmartin** [slackhq/node-slack-sdk#188]
Hi!
Just noticed that the `MemoryDataStore` no longer is the default when you create a new `RtmClient`, but I couldn't find anything stating why.

Wouldn't it make more sense to default to creating a data store, and rather have the users explicitly disable it if they don't want it? I guess it comes down to if most users would want a data store or not, but nonetheless not having one by default makes the migration path from version 1 to 2 one step more confusing.

**Comment by ekmartin** [comment]
Another option would be to throw an error with a helpful message if the user tries to access the non-existent `dataStore`'s methods.

**Comment by l12s** [comment]
The reasoning here was that some folks were concerned about the amount of memory the client was using.

I'll flip the behavior around so that if it's undefined you get one, but if it's falsy you don't

**Comment by l12s** [comment]
Fixed by #225

**Comment by ekmartin** [comment]
Sounds like a good solution - definitely agree that it should be easy to turn off.
