### ISSUE TITLE
RTM_EVENTS.MANUAL_PRESENCE_CHANGE Doesn't Fire

### ISSUE THREAD

**Issue by g5codyswartz** [slackhq/node-slack-sdk#201]
It seems the RTM_EVENTS.PRESENCE_CHANGE event does fire but not the manual one.
v2.3.0

**Comment by l12s** [comment]
Hey, I couldn't replicate this on either the current client or the `2.3.0` client. Mind sending me a code snippet where you'd expect to see this happen?

Also, how are you changing your presence?

**Comment by ctsstc** [comment]
I'm setting my away status via /away command as well as the UI

Here's an example of the code & a video: 
http://pastebin.com/GyDFALVj
http://screencast.com/t/N7HPQj22Y

**Comment by l12s** [comment]
Thanks for the context, will take a look

**Comment by l12s** [comment]
Ok, and to confirm. You've used an API token for coder.swartz account to connect to the RTM API? I believe you should only see `manual_presence_change` when the user who manually changes their presence is the same as the user that connects to the RTM API stream.

**Comment by l12s** [comment]
Yep, I just checked this and you should only see `manual_presence_change` when you're connected as the user who's manually changing their presence. I'm going to close this issue, but please reopen if you're both connected as that user and not seeing the event.

**Comment by ctsstc** [comment]
Whoops used two accounts to create the ticket and comment. 
Thanks for the heads up about this and confirming the functionality.
