### ISSUE TITLE
RTM_EVENTS.CHANNEL_JOINED isn't fired. MESSAGE is fired instead.

### ISSUE THREAD

**Issue by marceloschmidt** [slackhq/node-slack-sdk#209]
It seems to me that the CHANNEL_JOINED event is never fired.
Instead, the client receives a MESSAGE event, with type: 'message' and subtype: 'channel_join'.
Thanks!

**Comment by l12s** [comment]
So, it should only fire when the user connected to the API joins a channel. So if you use your own token to connect to the API and then join a channel, you'd expect to see a `channel_joined` come through. `channel_join` is for the more general case of a team member joining a channel.

**Comment by marceloschmidt** [comment]
Ah, I see! Is that a "confirmation" message for when we issue a `bot join that room` command, then?

**Comment by l12s** [comment]
If what you mean is:
* you connect to the RTM API as a bot user
* as the same bot user you make a [`channels.join`](https://api.slack.com/methods/channels.join) API call

... you'd expect to see a `channel_joined` event come down over the RTM stream. If the users don't match, you'd expect to see a `channel_join` event instead.

**Comment by marceloschmidt** [comment]
Thank you!

**Comment by rickul** [comment]
Hi, I have a similar issue.
channel_joined is only fired when the bot joins a channel.
channel_join is never fired. Shouldn't this be fired when any team member joins any channel?

**Comment by DEGoodmanWilson** [comment]
No, that event is only fired for your bot. Watch for `message.channel_join` for other members. This is a subtype of the `message` event.
