### ISSUE TITLE
Subtype CHANNEL_LEAVE isn't set for bot removal message

### ISSUE THREAD

**Issue by pukhalski** [slackhq/node-slack-sdk#211]
No ability to detect whether it's a simple text message or not.

```JS
{ type: 'message',
  user: 'USLACKBOT',
  text: 'You have been removed from #test by <@U0YBNG4TF|pukhalski>',
  user_team: 'T0YBMKJ4X',
  team: 'T0YBMKJ4X',
  user_profile: 
   { avatar_hash: 'sv1444671949',
     image_72: 'https://a.slack-edge.com/0180/img/slackbot_72.png',
     first_name: 'slackbot',
     real_name: 'slackbot',
     name: 'slackbot' },
  channel: 'D0YBJDMFY',
  ts: '1463092726.000009' }
```

**Comment by l12s** [comment]
You should only get `channel_leave` events when someone else leaves a channel.

Your user should have received a [`channel_left` event](https://api.slack.com/events/channel_left) though, although I'm not 100% sure of the behavior when you're kicked by someone else. Mind checking your logs to see if you got that?

**Comment by pukhalski** [comment]
Yes. As for events, everything's ok. But apart from event you're receiving that kind of message as well. So it feels like a duplication. I decided to go on with listening to RTM_EVENTS.MESSAGE only, since in any case it sends all the events as well.

**Comment by l12s** [comment]
Ok, sounds good.
