### ISSUE TITLE
Bots cannot @mention groups?

### ISSUE THREAD

**Issue by ctsstc** [slackhq/node-slack-sdk#213]
I have not been able to find any documentation on this and assume it's been overlooked or is like this for a reason.

Edit/PS: Is there any community chat group set up around slack bot/api implementation. I'd love to be inside of a slack group that is active in this field. Ironically I don't think slack has much in terms of public chats so maybe I'll look on discord; I couldn't find anything on gitter.

**Comment by esses** [comment]
to the PS... you may want to try the [Slack Developer Hangout](http://dev4slack.xoxco.com/)

**Comment by DEGoodmanWilson** [comment]
Bots are not allowed to @mention groups or @here. This is a limitation of the Slack platform itself, and not the SDK, I'm sorry to say.
