### ISSUE TITLE
Two NPM pages causes confusion

### ISSUE THREAD

**Issue by foiseworth** [slackhq/node-slack-sdk#216]
Currently there are two NPM pages for the project:
https://www.npmjs.com/package/slack-client
https://www.npmjs.com/package/@slack/client

The old page states that ```We'll dual-publish both @slack/client and slack-client until at least 2.1.0 is released, and possibly past that, but please switch over before then.```

However the current version on the old page is 2.0.4 so a user would be unaware that the project has transferred over.

**Comment by Everesty** [comment]
There is [a part of the old package's readme](https://www.npmjs.com/package/slack-client#package-name-change) that states the move over? I guess it doesn't really mention that the transfer has _already_ happened, but assuming they take the advice and move over, they'll likely notice.

**Comment by ekmartin** [comment]
Would help if [npm deprecate](https://docs.npmjs.com/cli/deprecate) was used on the old package though.

**Comment by l12s** [comment]
Thanks, oversight on my part. I'll do that and update the README.

**Comment by l12s** [comment]
Ok, fixed, thanks for catching this.

**Comment by foiseworth** [comment]
np - many thanks for the speedy action
