### ISSUE TITLE
Non-obvious use inside docker container

### ISSUE THREAD

**Issue by dharness** [slackhq/node-slack-sdk#218]
I have a very simple RTM app as follows

    var token = process.env.SLACK_API_TOKEN || '<my token>';

    var rtm = new RtmClient(token, { logLevel: 'debug' });
    rtm.start();

    rtm.on(CLIENT_EVENTS.RTM.AUTHENTICATED, function (rtmStartData) {
      console.log(`Logged in as ${rtmStartData.self.name} of team ${rtmStartData.team.name}, but not yet connected to a channel`);
    });

which connects outside of docker, but not inside. I expect that I need to properly expose the port on which the socket connects but I cannot find anywhere which port that might be.

Please advise.

**Comment by dharness** [comment]
I believe this is an issue with DNS inside docker containers. Closing.

**Comment by aoberoi** [comment]
@nicutimofte i've never seen this issue, but i can add one clarification. the RTM client does not need ports to be open for incoming connections. it does need to be able to lookup the hostname (DNS) and make outgoing connections to the internet. basically, if you can get `curl` to work inside your docker container, you should be able to use the RTM client in this package.
