### ISSUE TITLE
Is this API right for me?

### ISSUE THREAD

**Issue by vamichael** [slackhq/node-slack-sdk#236]
I'm trying to create a bot that listens to all public channels and every time anyone says anything  on a public channel, regardless if it includes an **@mention,** I want to send to a channel called **notifications*" the following

Username
channel name
the message itself, including a link to the message.

Is this doable with this API?  Does it have to be hosted somewhere, or can it "live" on the slack servers?

**Comment by Everesty** [comment]
Yes, it is doable. I don't really have the time to go into how right now, so I apologize on that note.

It has to be hosted by you, Slack won't host the bot for you.

I do, however, want to ask you why you want to do this? I don't see any purpose, but I may just be missing something.

**Comment by vamichael** [comment]
I get extremely frustrated when I see or hear a notification and then I
can't find out what caused the action. When you have dozens of channels and
red dots galore, slack becomes overwhelming. I'd just like to see a log of
all recent public events that I can jump too and see what caused the ding.

I've looked for slack user forums, but haven't seen anything useful. I wish
slack would create a forum. I don't like it when companies don't have one,
because it isolates their customers.

**Comment by Everesty** [comment]
Uh, there is a feature that shows you a list of times you've been mentioned (with basically everything you just asked for)

In fact, [there's even a Slack Help Center article on it.](https://get.slack.help/hc/en-us/articles/205240127-Using-mentions)

# On Desktop
'Tis simple, there's a little `@` button in the upper right corner of a chat: 

![yay for buttons](http://puu.sh/pD8tU/c21e6e8cd9.png)

It should show you a list of times you've been mentioned. If you'd like, there's also an option to include `@channel` mentions.

# On Mobile
(sorry for no images, too tired atm)

1. In the upper left you should see your team's icon, tap that.
2. Again, in the upper left of the drawer that slides out you should see "Home".
3. Tap it and one of the options will be "Mentions".

Again, 'tis simple.

---

As for other issues you may have in the future, consider looking **[at the Help Center](https://get.slack.help/)** or (if you can't find the resolution to a slack issue on the Help Center) consider [opening a support request.](https://playsharp.slack.com/help/requests/new)

**Comment by DEGoodmanWilson** [comment]
Closing, as this is a general Slack help request, rather than something specific to the project. You might also consider joining the Dev4Slack Slack team (sign up at dev4slack.xoxco.com), channel #sdk-node-slack-sdk
