### ISSUE TITLE
Basic Slack Message is not working

### ISSUE THREAD

**Issue by jadesym** [slackhq/node-slack-sdk#241]
For some reason, slack is no longer sending any messages.

```
import slack from '@slack/client';
const webClient = new slack.WebClient(<API_KEY>);
webClient.team.info((err, info) => {
  if (err) {
    console.log('Error:', err);
  } else {
    console.log('Team Info:', info);
  }
});
```

I cannot get even this basic version to work anymore. Nothing is being output. Anyone know why this is happening?

**Comment by DEGoodmanWilson** [comment]
Did you close this because you resolved the issue, @jadesym?

**Comment by jadesym** [comment]
Yeah, sorry about that. I fixed my error after I played with it a bit longer.

**Comment by DEGoodmanWilson** [comment]
No worries, just wanted to make sure!!
