### ISSUE TITLE
I do not understand how to delete messages via RTM bot objects...

### ISSUE THREAD

**Issue by nohir0** [slackhq/node-slack-sdk#249]
Slack API supports deleting messages via bot users,
as far as I understand with the "as_user=true" argument in api call.
In this case it is a RTM API call, not a Web API call.

It looks like this is also possible in the node-slack-sdk, but I am not able to reverse engineer the necessary code...

Something like:
```
var RTM_EVENTS = require('@slack/client').RTM_EVENTS;

rtm.on(RTM_EVENTS.MESSAGE, function handleRtmMessage(message) {
   rtm.chat.delete("<TIMESTAMP>", "<CHANNEL-ID>", "as_user=true");

```

This method "chat.delete" is available for the Web API in this wrapper,
but only a bot user is allowed to delete on behalf of another user.

The plan is to create a read only channel e.g. through deleting all messages from others than the channel owner....

Thanks for any hints in advance!

**Comment by nohir0** [comment]
ok, think I got it now.
Slack bot with RTM API allows only deletion of its own messages, not from other members.
To be able to call methods like chat.delete, a token from an admin account is necessary (with custom integration) to delete other users messages from a channel.

To be able to call a web api method like chat.delete, a personalized token from an admin user is required.  With this, a webhook configuration within slack is not necessary...

**Comment by DEGoodmanWilson** [comment]
From an admin user, or from the user who posted the message, presuming that message deletion hasn't been disabled. Yup!

**Comment by bolekkerous** [comment]
Hey, @nohir0 - I haven't found your email, so that's why I'm commenting here.

Have you managed to figure out the bot in the end? Would you be willing to share the source for that "read only" channel functionality bot? It's something that would help me since I'm looking for the same functionality and I don't know code very well yet.

**Comment by nohir0** [comment]
Hey @bolekkerous yes I figured it out and added some additional features like an "admin interface" too.
Sure, why not will push my code to github and let you know - just give me until next week cause Im still on holidays...

**Comment by nohir0** [comment]
@bolekkerous here my code for the Slack Read Only Channel with possibility to invite other member to post for admins...
https://github.com/nohir0/slack-channel-readonly

**Comment by bolekkerous** [comment]
@nohir0 - thanks a lot, I really appreciate it!
