### ISSUE TITLE
npm install @slack/client receiving a 403 error

### ISSUE THREAD

**Issue by twellspring** [slackhq/node-slack-sdk#257]
I am trying to install hubot-slack, which has a dependency on @slack/client.   The install is failing due to "user xxxx is not allowed to access package @slack/client : @slack/client"  Trying to install just @slack/client gets the same error.   I have tried from multiple servers/IPs and with multiple different versions of NPM.  Just updated NPM and tried again with same results.

Manually going to the URL  http://npm.riskalyze.com/@slack%2fclient  gives the same 403

```
# npm install -d @slack/client
npm info it worked if it ends with ok
npm info using npm@3.10.5
npm info using node@v5.10.1
npm info attempt registry request try #1 at 3:45:08 PM
npm http request GET http://npm.riskalyze.com/@slack%2fclient
npm http 403 http://npm.riskalyze.com/@slack%2fclient
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-d" "@slack/client"
npm ERR! node v5.10.1
npm ERR! npm  v3.10.5
npm ERR! code E403

npm ERR! user twells is not allowed to access package @slack/client : @slack/client
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/npm-debug.log
```

**Comment by DEGoodmanWilson** [comment]
Hi, sorry to be a pain, but would you reopen #256 with this new information, instead of opening a new issue?

**Comment by twellspring** [comment]
Not a pain.  I thought I had reported this but could not find the case so I figured I had not submitted it and closed the tab by mistake ... so I re-submitted.

**Comment by DEGoodmanWilson** [comment]
NP 😄
