### ISSUE TITLE
getDMByName finds some users but not others

### ISSUE THREAD

**Issue by andrewpbrett** [slackhq/node-slack-sdk#263]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
`getDMByName` finds some users but not others

#### Reproducible in:
{project_name} version: 3.0.0
OS version(s): Mac OSX
Device(s): n/a

#### Steps to reproduce:

1. create an rtm client, i.e. 

```var rtm = new RtmClient(obj.bot_access_token, {
      dataStore: new MemoryDataStore(),
      autoReconnect: true,
    });```

2. call `rtm.getDMByName("username")` for a username you know to be on the team

### Expected result:
Should return the DM channel for that user (it does for some users).

### Actual result:
Returns `undefined`

### Attachments:

**Comment by Everesty** [comment]
Is it possible you're calling `getDMByName` for people who haven't spoken with the bot before? I believe in that case there is no DM channel yet, and you'd instead need to either send a message to them to create the channel, or use the [`im.open` method, via the `WebClient`](https://api.slack.com/methods/im.open).

Just pure speculation, though.

**Comment by andrewpbrett** [comment]
That is, in fact, exactly what was happening. Impressive debugging from afar!
