### ISSUE TITLE
Incoming Webhook client missing in npm package

### ISSUE THREAD

**Issue by StefanoMagrassi** [slackhq/node-slack-sdk#266]
* [X] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [X] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [X] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
I've just installed the module from [npm](https://www.npmjs.com/package/@slack/client), but the `IncomingWebhook` client is totally missing...

It seems that something wrong happened on publishing the package...

**Comment by Everesty** [comment]
The version with the `IncomingWebhook` client hasn't been pushed to npm yet. Web hook support for this package was added 2 days ago, but the package hasn't been pushed since 2 weeks ago.

**Comment by StefanoMagrassi** [comment]
@Everesty ooooook  :wink:

The version number misled me 👍

**Comment by sneakersgames** [comment]
Yeah, well, maybe it would be time to update npm since following the docs/github leads to this:
`var wh = new IncomingWebhooks(url);
         ^

TypeError: IncomingWebhooks is not a function`

**Comment by DEGoodmanWilson** [comment]
Sorry y'all, been on vacation. Will get something new pushed out to NPM this week.

**Comment by alperg** [comment]
@DEGoodmanWilson, any update for the fix?

**Comment by danielmapar** [comment]
any news on this?

**Comment by DEGoodmanWilson** [comment]
Out as of just now!

**Comment by DEGoodmanWilson** [comment]
Out as of just now! v3.6.0

**Comment by danielmapar** [comment]
thanks a lot! :)
