### ISSUE TITLE
Create a snippet using an IncomingWebhook

### ISSUE THREAD

**Issue by sibelius** [slackhq/node-slack-sdk#273]
* [x] I've read and understood the [Contributing guidelines](./CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](./CODE_OF_CONDUCT.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

#### Description
How can I create a snippet using IncomingWebhook api?

if this is not possible, how should I do it?

I would like to create a snippet using an object or a string

**Comment by DEGoodmanWilson** [comment]
I am sorry to say that it is not possible to upload a snippet with incoming webhooks. You must use the [`files.upload` API](https://api.slack.com/methods/files.upload) and set the type to `snippet`.
