### ISSUE TITLE
Text formatting for `code` is broken on desktop clients

### ISSUE THREAD

**Issue by dhigginbotham** [slackhq/node-slack-sdk#274]
I've noticed recently that on desktop clients that the following formatting is broken:

```
`[foo|bar|baz]`
```

Instead of the expected code formatting, the ` ticks seems to be ignored.  After a little debugging, I noticed that the following formatting still works:

```
`[foo]`
```

This is only affecting the desktop slack clients (mobile client seems unaffected).  Sorry if this isn't the place for this as I have a sneaking suspicious it's related to the client and not the sdk.

Cheers :+1:

**Comment by Everesty** [comment]
> Sorry if this isn't the place for this as I have a sneaking suspicious it's related to the client and not the sdk.

You are indeed correct in your suspicion: this isn't the right place to be reporting this. None the less, it's super cool that you found this bug!

You should, however, totally report this to the _right_ people. Those people would be the lovlies who handle Slack's help desk: https://slack.com/help/requests/new
