### ISSUE TITLE
Removed app, no message

### ISSUE THREAD

**Issue by brunosiqueira** [slackhq/node-slack-sdk#99]
When the app is removed from Slack, I can't see any type of message received letting the client acknowledge that. I only have the ping messages stopped.
Is there a clear way of knowing that the app was removed?

**Comment by l12s** [comment]
Good question - let me ask our dev team and get back to you.

**Comment by vanm** [comment]
@brunosiqueira we listen for an "account_inactive" error and that seems to do the trick.

```javascript
slack.on 'error', (err) ->
  if err && err is 'account_inactive'
    # Handle inactive here...     
```

**Comment by brunosiqueira** [comment]
Hey Leah, thank you for your response.

I know that the "account_inactive error" is raised when the app is not
installed, but this happens only when the bot is connecting. After it is
connected already, the "error" callback is not called anymore. The bot
stays up and working as if the communication with slack was working
properly. The only difference is that the client stops pinging.

Bruno Siqueira

2016-01-14 23:26 GMT+00:00 Van Miranda <notifications@github.com>:

**Comment by brunosiqueira** [comment]
Revisiting this issue, I did some tests with the autoReconnect true and false.
If the autoReconnect is true, it ignores account_inactive errors. It doesn't even emits the error callback. If the autoReconnect is false, it does emit the error when connecting, but if I am already connected and I remove the app it generates no info.

I tried in the 'close' callback calling the reconnect() method. And it does work perfectly (calling the 'error' callback). The problem is that if I call reconnect() when the internet connection is off, I can generate duplicated connections and messages when reconnected. This happen because, as far as I understood, the socket client reconnects automatically when the internet is off (independently of the autoReconnect param).

Does the version 2.0.0 works differently from this one in that matter?

**Comment by vanm** [comment]
@brunosiqueira re: the duplicate connections on reconnect(), I have a brute force (and hacky) approach to prevent that here: #66.  I think 2.0.0 aims to address this in a more comprehensive overhaul with tests but I haven't checked it out yet.

**Comment by brunosiqueira** [comment]
Thank you, @vanm ! But in the #93 issue we discussed how complex it is to install other options other than the central npm repo for the slack-client due to the coffee script compiler. To test your version shouldn't you have a release in your repo?

**Comment by vanm** [comment]
I did a hacky "release" just by generating the JS and committing it in this
branch. It's a bit outdated.

https://github.com/vanm/node-slack-client/tree/ws-and-team-migration-fixes

I think the best course of action is to use the beta as you are attempting
but you can always test this branch and see how it works for you.

**Comment by l12s** [comment]
So, I think that `>= 2.0.0` _should_ resolve this issue. The RTM client in that release checks the error type if it's unable to connect.

If it's one of [the unrecoverable errors](https://github.com/slackhq/node-slack-client/blob/03743068caa535f15a636da164953f402d1899c5/lib/clients/rtm/client.js#L18) it will disconnect, (passing an error message starting with `unrecoverable failure...`)[https://github.com/slackhq/node-slack-client/blob/03743068caa535f15a636da164953f402d1899c5/lib/clients/rtm/client.js#L224]

That's only helpful when you're reconnecting though. I'll look into what RTM events are sent if / when the bot is removed and see what the best way to handle the removal, aside from responding to the failure to `rtm.start`, should be.

**Comment by DEGoodmanWilson** [comment]
There are at this time no events sent with a bot is removed. Rather, the bot's connection is dropped, and it is up to the bot to detect the failure upon reconnect. So, Leah's solution is the only one available. At this time.
